# The "Sponsor" button on the repository page leads to the donation section of the README
custom: ["https://github.com/tirex999/2x2080ti-nvlink-44gb#%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%82%D1%8C-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82", "https://yoomoney.ru/to/4100119356331418"]
